"""initial migration

Revision ID: 05018879706b
Revises: 
Create Date: 2021-01-05 11:24:41.536758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05018879706b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('surname', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_author_surname'), ['surname'], unique=True)

    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('book',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('favStat', sa.Integer(), nullable=True),
    sa.Column('noStat', sa.Integer(), nullable=True),
    sa.Column('bookauthor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookauthor'], ['author.id'], ),
    sa.PrimaryKeyConstraint('title')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_title'), ['title'], unique=False)

    op.create_table('usersbooks',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['title'], ['book.title'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersbooks')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_title'))

    op.drop_table('book')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_password'))

    op.drop_table('user')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_surname'))
        batch_op.drop_index(batch_op.f('ix_author_name'))

    op.drop_table('author')
    # ### end Alembic commands ###
