"""empty message

Revision ID: b97775a02eca
Revises: c3e08213a0d2
Create Date: 2021-01-11 16:43:57.406972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97775a02eca'
down_revision = 'c3e08213a0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downvotes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('upvotes')
        batch_op.drop_column('downvotes')

    # ### end Alembic commands ###
